name: "Pull Request Labeler"
on:
  pull_request: # TODO: change this to pull_request_target when permissions change is in master

permissions:
  contents: read
  pull-requests: write
  # issues: write

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Request Labeler
        uses: actions/labeler@v3
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true
      - name: Label the PR size
        uses: codelytv/pr-size-labeler@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_max_size: "10"
          s_max_size: "100"
          m_max_size: "500"
          l_max_size: "1000"
          fail_if_xl: "false"
          # message_if_xl: >
          #   'This PR exceeds the recommended size of 1000 lines.
          #   Please make sure you are NOT addressing multiple issues with one PR.
          #   Note this PR might be rejected due to its size.â€™
